#!/bin/bash
#pull changes from develop and return to your branch

#get commit message stop execution if it was not provided
msg=$1
if [ $# -eq 0 ]; then
    echo "Please provide a commit message, as in:"
    echo "./git-pull 'feature x em desenvolvimento'"
    exit 1
fi

#get current branch
branch=$(git rev-parse --abbrev-ref HEAD)

#prepare to push
echo "Committing branch changes, without pushing them..."
git add -A
git commit -m "$msg"

echo "Checkouting to develop and pulling changes..."
git checkout develop
git pull

echo "Returning to original branch"
git checkout $branch
git branch
