#!/bin/bash
# obtainSamples - Script para obtencao do fabricSamples
# colocado em um novo diretorio criado chamado fabricSamples a
# partir do diretorio atual
# -------
# Alteracao do path do para já incluir os binarios do fabric
# (Rodar com . ./obtainSamples para atribuir corretamente)
# Alteracao temporaria altera somente o bash corrente
# Alteracao permanente altera o arquivo utilizado para criacao

obtemFabricSamples(){
        # Excluindo estrutura se ja existente
        #echo Excluindo diretorios 
        #sudo rm -r fabricSamples

        # Criando estrutura de diretorios
        echo Criando diretorios
        mkdir fabricSamples
        cd fabricSamples

        # Obtendo os Samples
        echo Obtendo Samples
        curl -sSL https://bit.ly/2ysbOFE | bash -s
}

clear
if [[ -d "fabricSamples" ]]; then
	echo "Samples do Hyperladger Fabric encontrados, continuando..."
else
	echo  "Deseja baixar a estrutura de diretorios dos Samples do Hyperledger Fabric ?( s / n)" 
	read simounao
	if [ "$simounao" == s ]; then
		obtemFabricSamples
	fi
fi


echo "Saindo ..."
