#!/bin/bash

# source containing env values
source ../api-2.0/.env

#install mysql
# sudo apt install default-mysql-server

#set systemd
sudo systemctl disable mysql
sudo systemctl start mysql

#create carbon user with low password policy and all permissions
#sudo mysql --execute "SET GLOBAL validate_password.policy=LOW"
sudo mysql --execute "CREATE USER 'carbon'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD'" 
# create user to any host (allow non-localhost calls)
sudo mysql --execute "GRANT ALL ON *.* TO 'carbon'@'localhost' WITH GRANT OPTION"
sudo mysql --execute "CREATE USER 'carbon'@'%' IDENTIFIED BY '$MYSQL_PASSWORD'"
sudo mysql --execute "GRANT ALL ON *.* TO 'carbon'@'%' WITH GRANT OPTION"

#create carbon db
mysql -ucarbon -p$MYSQL_PASSWORD --execute "source carbon.sql"
