#!/bin/bash
#regenerate sequelize models using sequelize-auto and recreate carbon DB

#only try to start mysql if it is not running already, otherwise sudo would be invoked in vain
start-mysql() {
  if [[ $(ps aux | grep mysql | grep -v grep) ]]; then
    echo "MySQL already running"
  else
    sudo systemctl start mysql
    echo "Started MySQL"
  fi
}

#set path to script's path
cd "$(dirname "$0")"

#run mysql
start-mysql

#create carbon db again
mysql -u carbon -p12345678 --execute "source carbon.sql"

#recreate sequelize models
cd sequelize-auto
npm install
node node_modules/sequelize-auto/bin/sequelize-auto -o "./models" -h localhost -e mysql --caseModel c --caseProp c -d carbon -u carbon -x 12345678 -p 3306

rm -rf ../../api-2.0/models
mv models ../../api-2.0

echo "Carbon DB recreated"
echo "Sequelize models recreated"

#o comando -t é opcional e deve ser usado caso se deseje criar o modelo sequelize de apenas uma tabela específica.

# node node_modules/sequelize-auto/bin/sequelize-auto -o "./models" -h localhost -e mysql --caseModel c --caseProp c -d carbon -u carbon -x 12345678 -p 3306 -t specific_table_else_all