name: Caliper benchmark
version: "2.0.0"

caliper:
  blockchain: fabric

channels:
  - channelName: mychannel
    contracts:
    - id: erc1155

organizations:
  - mspid: CarbonMSP
    identities:
      certificates:
      - name: 'Admin'
        clientPrivateKey:
           path: '../artifacts/channel/crypto-config/peerOrganizations/carbon.example.com/users/Admin@carbon.example.com/msp/keystore/965c8b257ebd2020c6488bb02065280b7ad76ad5ba21bfd57810b419144a4fe9_sk'
        clientSignedCert:
          path: '../artifacts/channel/crypto-config/peerOrganizations/carbon.example.com/users/Admin@carbon.example.com/msp/signcerts/cert.pem'
    connectionProfile:
      path: './networks/localconnection.json'
      discover: true