name: Caliper benchmark
version: "2.0.0"

caliper:
  blockchain: fabric

channels:
  - ChannelName: mychannel
    contracts:
    - id: erc1155

organizations:
  - mspid: CarbonMSP
    identities:
      certificates:
      - name: 'Admin'
        clientPrivateKey:
          # path: '/etc/data/peerOrganizations/carbon.example.com/users/Admin@carbon.example.com/msp/keystore/priv_sk'
          #path: '/tmp/admin/keystore/cd3edd64c313a6b50a13dd7b87e9fa7001919c169b6ab963adbccf1484eda1bf_sk'
          path: '../artifacts/channel/crypto-config/peerOrganizations/carbon.example.com/users/Admin@carbon.example.com/msp/keystore/e46281b3040531c34e3c48d690e13894f2ccbfddc21718ac6b4203c6e90c95d2_sk'
        clientSignedCert:
          # path: '/etc/data/peerOrganizations/carbon.example.com/users/Admin@carbon.example.com/msp/signcerts/Admin@carbon.example.com-cert.pem'
          #path: '/tmp/admin/signcerts/cert.pem'
          path: '../artifacts/channel/crypto-config/peerOrganizations/carbon.example.com/users/Admin@carbon.example.com/msp/signcerts/cert.pem'
    connectionProfile:
      path: '/tmp/config/connection-carbon.json'
      discover: true