version: "2.1"

networks:
  carbon-net:
    external: true

services:
  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:2.1
    dns_search: .
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - ORDERER_GENERAL_LISTENPORT=7050
      # - ORDERER_GENERAL_TLS_TLSHANDSHAKETIMESHIFT=200h
      # - ORDERER_GENERAL_CLUSTER_TLSHANDSHAKETIMESHIFT=200h
      # - ORDERER_GENERAL_AUTHENTICATION_NOEXPIRATIONCHECKS=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 7050:7050
      - 8443:8443
    networks:
      - carbon-net
    volumes:
      - ./channel/genesis.block:/var/hyperledger/orderer/genesis.block
      - ./channel/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
      - ./channel/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/var/hyperledger/orderer/tls
      # - /var/pavan/orderer:/var/hyperledger/production

  couchdb0:
    container_name: couchdb0
    image: couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5984:5984
    networks:
      - carbon-net

  couchdb1:
    container_name: couchdb1
    image: couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 7984:5984
    networks:
      - carbon-net

  couchdb2:
    container_name: couchdb2
    image: couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 8984:5984
    networks:
      - carbon-net

  peer0.carbon.example.com:
    container_name: peer0.carbon.example.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LOGLEVEL=info
      - CORE_PEER_LOCALMSPID=CarbonMSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=carbon-net

      - CORE_PEER_ID=peer0.carbon.example.com
      - CORE_PEER_ADDRESS=peer0.carbon.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.carbon.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # Peer used to bootstrap gossip within organisation
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.carbon.example.com:8051
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.carbon.example.com:7051

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb0
    ports:
      - 7051:7051
    volumes:
      - ./channel/crypto-config/peerOrganizations/carbon.example.com/peers/peer0.carbon.example.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./channel/crypto-config/peerOrganizations/carbon.example.com/peers/peer0.carbon.example.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      # - /var/pavan/peer0-carbon:/var/hyperledger/production
      # - ./channel/:/etc/hyperledger/channel/
    networks:
      - carbon-net

  peer0.cetesb.example.com:
    container_name: peer0.cetesb.example.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LOGLEVEL=info
      - CORE_PEER_LOCALMSPID=CetesbMSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=carbon-net

      - CORE_PEER_ID=peer0.cetesb.example.com
      - CORE_PEER_ADDRESS=peer0.cetesb.example.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      # - CORE_PEER_CHAINCODEADDRESS=peer0.cetesb.example.com:7052
      # - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # Peer used to bootstrap gossip within organisation
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.cetesb.example.com:12051

      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.cetesb.example.com:11051

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb1
    ports:
      - 11051:11051
    volumes:
      - ./channel/crypto-config/peerOrganizations/cetesb.example.com/peers/peer0.cetesb.example.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./channel/crypto-config/peerOrganizations/cetesb.example.com/peers/peer0.cetesb.example.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      # - /var/pavan/peer0-cetesb:/var/hyperledger/production
    networks:
      - carbon-net

  peer0.ibama.example.com:
    container_name: peer0.ibama.example.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LOGLEVEL=info
      - CORE_PEER_LOCALMSPID=IbamaMSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=carbon-net

      - CORE_PEER_ID=peer0.ibama.example.com
      - CORE_PEER_ADDRESS=peer0.ibama.example.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      # - CORE_PEER_CHAINCODEADDRESS=peer0.ibama.example.com:7052
      # - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # Peer used to bootstrap gossip within organisation
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.ibama.example.com:12051

      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ibama.example.com:13051

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb2
    ports:
      - 13051:13051
    volumes:
      - ./channel/crypto-config/peerOrganizations/ibama.example.com/peers/peer0.ibama.example.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./channel/crypto-config/peerOrganizations/ibama.example.com/peers/peer0.ibama.example.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      # - /var/pavan/peer0-ibama:/var/hyperledger/production
    networks:
      - carbon-net

  ipfs:
    container_name: ipfs
    image: ipfs/kubo:master-latest
    environment:
      - IPFS_PATH=/data/ipfs
    ports:
      # Gateway
      - 8080:8080
      # API, private
      - 5001:5001
      # Swarm
      - 4001:4001/udp
      - 4001:4001/tcp
    networks:
      - carbon-net

  # node_app:
  #   container_name: node_app
  #   # build: ../api-2.0
  #   build:
  #     context: ../
  #     dockerfile: ./api-2.0/Dockerfile
  #   ports: 
  #     - 4000:4000
  #   expose:
  #     - '4000'
  #   volumes: 
  #       - ./:/artifacts
  #   #   - ../api-2.0/:/app   #sincroniza arquivos do container e do repositório local
  #   #   - /app/node_modules  #não permite que as alterações locais modifiquem o node_modules do container
  #   #   - ./:/app/artifacts
  #   #   - ../network_org1.yaml:/app/network_org1.yaml
  #   env_file: 
  #     - ../api-2.0/.env
  #   networks:
  #     - carbon-net
  #   depends_on:
  #     database:
  #       condition: service_healthy

  # database:
  #   container_name: database
  #   environment:
  #     MYSQL_PASSWORD: 12345678
  #     MYSQL_ROOT_PASSWORD: 12345678
  #     MYSQL_USER: carbon
  #     MYSQL_DATABASE: carbon
  #   build:
  #     context: ../database/
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3306:3306
  #   expose:
  #     - '3306'
  #   networks:
  #     - carbon-net
  #   tty: true
  #   command: /bin/bash


  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    hostname: mysqldb
    environment:
      MYSQL_DATABASE: 'carbon'   
      MYSQL_USER: 'carbon'
      MYSQL_PASSWORD: '12345678'      
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ../database/scripts/:/docker-entrypoint-initdb.d
      # - ../database/mysql:/etc/mysql/my.cnf.d
    networks:
      - carbon-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 30s
      timeout: 20s
      retries: 4
      # - '../database/db:/var/lib/mysql'
    # command: bash -c "chmod +x ./grant-access-db.sh" 